ProviderType: "vsphere"
EngineType: "capv"
URL: "172.60.0.150"
Username: "administrator@vsphere.local"
Password: "NetApp1!!"
Datacenter: "NetApp-HCI-Datacenter-01"
ResourcePool: "*/Resources"
Datastore: "NetApp-HCI-Datastore-01"
ManagementNetwork: "NetApp HCI VDS 01-HCI_Internal_mNode_Network"
StorageNetwork: "NetApp HCI VDS 01-HCI_Internal_Storage_Network"
Folder: "mgmt"
OVA:
  BootstrapTemplate: "http://storage.googleapis.com/capv-images/release/v1.17.3/ubuntu-1804-kube-v1.17.3.ova"
  NodeTemplate: "http://storage.googleapis.com/capv-images/release/v1.17.3/ubuntu-1804-kube-v1.17.3.ova"
  LoadbalancerTemplate: "http://storage.googleapis.com/capv-images/extra/haproxy/release/v0.6.0-rc.2/capv-haproxy-v0.6.0-rc.2.ova"
SSH:
  Username: "capv"
  AuthorizedKeys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDW7BP54hSp3TrQjQq7O+oprZdXH8zbKBww/YJyCD9ksM/Y3BiFaCDwzN/vcRSslkn0kJDUq7TxmKp9bEZLTXqAiRe7GflNGoiAUuNY9EWnxt305HIkBs+OEdV6KDtnlm9sRAADflzbDi6YiMjbwNcfoRoxTgpo6BNlzv9Y3prDXiwEjxvosK+4WWIVTTEh33nNvQ5iQhPqBNgURmjQx9EDXFIRdZzA8OykPNLIqFdzmxGZWWxFbW/n6nEl/96b6w7Gx0YgzTSLs+6WAQl8SMP9l22L6puitpjihRw9cWRJ9r6x1eLqgc5Sv7gDKOMXghbmS6hy+AtrxCPPJgq7Mguc5bPAqTZlYMy98dxpHVqtAnBso/9aLOzAXX6At/0QUIwMP693B11NTGniIMtBxnD/yWvGoxTXNmXcTvj13cTzSv9czaGSJ+MTRIugtgyouZADfs8v59NV9KoaEq8umy6WEhmtw5wkjzvC5KK4N2bsM1N+8lSIKxYWxWZFsdYBP8ep442Z/2T5R8y8c5cp7tQqqapDt8JPJ0OPq3sn30BO3X8MgvmoB39j4Cqok1y9VuouPH4RalRLMR7KrASdlFengjt0vWBUoNaEuxRdJR2eOM6SpZh6YGqLdQH1MLaBOzDTH2tTLyTXCOSJpve6ZHOPbjS2BF34a1Kj52NTFtiYTw=="
Local: true
ClusterName: "capv-management"
ControlPlaneCount: 1
WorkerCount: 2
KubernetesVersion: "v1.17.3"
KubernetesPodCidr: ""
KubernetesServiceCidr: ""
Kubeconfig: ""
Namespace: "capv-management"
LogFile: "/tmp/cake.log"
GithubToken: ""